POST http://localhost:8080/property/register
Content-Type: application/json

{
    "id" : "SLACK",
    "value": ""
}

###
POST http://localhost:8080/property/register
Content-Type: application/json

{
    "id" : "USER_ID",
    "value": ""
}

###
POST http://localhost:8080/property/register
Content-Type: application/json

{
    "id" : "USER_PASSWORD",
    "value": ""
}

###
POST http://localhost:8080/property/slack

###

POST http://localhost:8080/department/crawl

###

POST http://localhost:8080/course/crawl
Content-Type: application/json

{
  "departmentId" : "006751",
  "courseType": "ALL"
}

###

POST http://localhost:8080/course/crawl
Content-Type: application/json

{
    "departmentId" : "127113",
    "courseType": "ALL"
}
###

POST http://localhost:8080/course/crawl
Content-Type: application/json

{
    "departmentId" : "127114",
    "courseType": "ALL"
}
###

POST http://localhost:8080/course/crawl
Content-Type: application/json

{
    "departmentId" : "127428",
    "courseType": "ALL"
}

###

POST http://localhost:8080/course/like
Content-Type: application/json

{
    "courseId" : "3215",
    "memberId": "jake"
}

###
GET http://localhost:8080/course/crawl-list
Content-Type: application/json

###
