POST http://localhost:8080/department/crawl

###

POST http://localhost:8080/course/crawl
Content-Type: application/json

{
  "departmentId" : "126904",
  "courseType": "ALL"
}

###

POST http://localhost:8080/course/like
Content-Type: application/json

{
    "courseId" : "0824",
    "memberId": "jake"
}

###
